/** Notion connector — WRITE (save-plan document) + verify by page retrieve. */
import { Client } from "@notionhq/client";
import { requireEnv } from "../env";
import type { Evidence, VerificationResult } from "../types";

let client: Client | null = null;
export function notion(): Client {
  requireEnv("notion");
  client ??= new Client({ auth: process.env.NOTION_API_KEY! });
  return client;
}

const text = (content: string) => [{ type: "text" as const, text: { content: content.slice(0, 1900) } }];

export type SavePlanInput = {
  accountName: string;
  headline: string;
  rationale: string;
  evidence: Evidence[];
  actions: string[];
};

export async function createSavePlan(
  input: SavePlanInput,
): Promise<{ id: string; url: string; title: string }> {
  const title = `Save plan — ${input.accountName}`;
  const page = await notion().pages.create({
    parent: { type: "page_id", page_id: process.env.NOTION_PARENT_PAGE_ID! },
    properties: { title: { title: text(title) } },
    children: [
      { object: "block", type: "callout", callout: { rich_text: text(input.headline), icon: { type: "emoji", emoji: "⚠️" } } },
      { object: "block", type: "heading_2", heading_2: { rich_text: text("Why this account is at risk") } },
      { object: "block", type: "paragraph", paragraph: { rich_text: text(input.rationale) } },
      { object: "block", type: "heading_2", heading_2: { rich_text: text("Evidence") } },
      ...input.evidence.slice(0, 12).map((e) => ({
        object: "block" as const,
        type: "bulleted_list_item" as const,
        bulleted_list_item: {
          rich_text: [
            { type: "text" as const, text: { content: `${e.source.toUpperCase()} — ${e.label}: ` }, annotations: { bold: true } },
            { type: "text" as const, text: { content: e.detail.slice(0, 1200), link: e.url ? { url: e.url } : null } },
          ],
        },
      })),
      { object: "block", type: "heading_2", heading_2: { rich_text: text("Recovery actions") } },
      ...input.actions.slice(0, 10).map((a) => ({
        object: "block" as const,
        type: "to_do" as const,
        to_do: { rich_text: text(a), checked: false },
      })),
      {
        object: "block",
        type: "paragraph",
        paragraph: { rich_text: text(`Generated by Keel at ${new Date().toISOString()}. Every action below was policy-checked and verified by read-back.`) },
      },
    ],
  });
  const url = (page as { url?: string }).url ?? `https://notion.so/${page.id.replace(/-/g, "")}`;
  return { id: page.id, url, title };
}

/** Verification: retrieve the page and confirm it exists and is not trashed. */
export async function verifyPage(id: string): Promise<VerificationResult> {
  const checkedAt = new Date().toISOString();
  try {
    const page = (await notion().pages.retrieve({ page_id: id })) as {
      id: string;
      archived?: boolean;
      in_trash?: boolean;
    };
    const live = Boolean(page.id) && !page.archived && !page.in_trash;
    return {
      verified: live,
      method: "notion.pages.retrieve(id)",
      detail: live ? `Page ${page.id} exists and is live.` : "Page is archived or in trash.",
      checkedAt,
    };
  } catch (err) {
    return {
      verified: false,
      method: "notion.pages.retrieve(id)",
      detail: `Re-fetch failed: ${(err as Error).message}`,
      checkedAt,
    };
  }
}
